language: node_js
node_js: '11'
before_install:
- rvm install 2.4.1
before_script:
- gem install sass
- yarn install
script: bash release.sh
deploy:
  provider: releases
  api_key:
    secure: aaZUjWYwEtVhFIBepDJrww+RO8tN8Gd5HvQgOvOazXip7JILGNxLYwCjzUjsNmPuyrbf9z2y8vZkhj1TU9HG0RxU+BR5HIHBUTRdUU0hnmcaHf3K3TjT3xk6hpwUlx9DCcbCzyFRhVQ2XS6geyb+HmcB9PZD8Uk4iF/1knY+zveqErKtXH911n3DmSZTlrst1SJu9GlBaO3U6XU0rgv1d2wE4w0u8hMnHJCOHxJRaQ3vQTutCfS6kzhZj2REjuh8wNjZ77narMKaGWJKyDFoOG4bhcWP+vQhwB+7ZhV7fGzk8rKgB6zgnzYISMhBeGA78oCn3OYI7cYjVE/rzgMGNY4vk+yjjaYkYNLEXd7OIWA4ZeK4MX2gh2uSWMXcUzCp/TkY2pIMffzAGU3XWKIqOc5Mx2UVkymHCjmLVGIe35Q5WRArAq/cW1Yy8OWodK0p2dfKlnXNewJ6MGE01OukJPsbdSfRB7fNVAVK10Z4K1qh8nG9dMItFJAMsX/54I3mb++FnRMLrTEUOkCjOUXcDtPNaBAThkxDewiLQauNHByG+ENaFhROZ5A4iBi8ciisBygNzziNBkJ4Z6XQ/e+/kXzmiIJKG9ptJDXZYM3df+HrAA+19p3wGknhiDv9wH0OuO8mn37fsFZ2EMYPhoOXEd6fl70Y92vhgE+Am6aqZAA=
  file:
    - april-$TRAVIS_TAG.tar.gz
    - april-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    repo: dArignac/april
    tags: true